### PR TITLE
Version should be overridable by custom version string

### PR DESCRIPTION
**Pull request by peanutbother**
see https://github.com/rhysd/electron-about-window/issues/51

### CODE REVIEW

**Comment by rhysd** [comment]
Please avoid formatting.

**Comment by rhysd** [comment]
@peanutbother BTW why author of the commits is different from you? They are committed by @eldnub

**Comment by peanutbother** [comment]
> @peanutbother BTW why author of the commits is different from you? They are committed by @eldnub

this is because I have different workplaces with different gpg keys because I maintain private git servers with gpg signing, so I sometimes commit as my ghost account




> Please avoid formatting.

I accidentally formatted because I use prettier in vscode which does this automatically.
I will rebase ASAP

**Comment by rhysd** [comment]
> this is because I have different workplaces with different gpg keys because I maintain private git servers with gpg signing, so I sometimes commit as my ghost account

OK. I wanted to confirm other's commits are not in this branch for sure.

> I accidentally formatted because I use prettier in vscode which does this automatically.
I will rebase ASAP

Thanks. Just merging current master into this branch and run `npm run prettier` would be fine.

**Comment by rhysd** [comment]
Closing in favor of #53

**Pull request closed without merging**
