### PR TITLE
update to support an array of css paths, and more flexible productName

### LINKED ISSUE #21: increase flexibility of css_paths and productName
it would be helpful to support an array of css_paths

and it would be helpful to allow productName to be specified in the options, rather than being read only from package.json

(PR coming)

### PR DESCRIPTION
**Pull request by starpit**
this PR allows for productName to be specified in the options structure, and allows for css_paths to be an array of paths

Fixes #21

### CODE REVIEW

**Comment by rhysd** [comment]
Thank you for patch. I'll review this.

**Comment by rhysd** [comment]
@starpit 

Please update README.md also.
- Add new property `productName`
- Change the type of `css_name` to `string | string[]`

**Comment by starpit** [comment]
thank you @rhysd for the careful review of my PR. i have updated it accordingly.

**Comment by rhysd** [comment]
@starpit 

I published v1.10.0. Please note that I renamed `productName` to `product_name` for aligning to other properties. (Property names are in snake_case, not in camelCase because of historical reason)

**Comment by starpit** [comment]
thank you. npm info shows this:
```
     '1.10.0': '2018-02-19T02:29:10.662Z' },
```
did you mean 1.11.0?

that's fine, re: productName; i was trying to be consistent with the field name that electron itself uses (productName), but understand your desire for consistency within your module.

**Comment by rhysd** [comment]
ah, sorry, I meant 1.11.0.

**Pull request merged**
