### PR TITLE
Added bug text  to allow dynamic modification of message

### PR DESCRIPTION
**Pull request by jhnferraris**
The rationale behind here is to allow clients to set their own bug text

### CODE REVIEW

**Comment by rhysd** [comment]
#15 was merged. Do you still need this PR to be merged?

**Comment by jhnferraris** [comment]
Yes. It would be better for apps to have their own message. 

App A: “experiencing an issue? Submit a report”
App B: “If you’re experiencing issues, you can email us at.”

Thanks!

**Comment by rhysd** [comment]
ok, please resolve conflict. Please note that when #14 is fixed, this feature may have some breaking change (in the case, of course I bump up major version of this package).

**Comment by jhnferraris** [comment]
@rhysd How will I resolve this? I do not have write access.

screenshot from 2018-01-22 17-19-21

**Comment by jhnferraris** [comment]
Figured how to do it. Here's the updated PR

**Comment by rhysd** [comment]
Thanks.

**Comment by jhnferraris** [comment]
@rhysd Is this already published?

**Comment by rhysd** [comment]
Not yet. I'm now on biz trip to SF and I don't have a machine to publish an npm package. So let me publish a new version after backing to Japan. New version should come at end of this week. Sorry for making you wait.

**Comment by rhysd** [comment]
@jhnferraris @will-stone I published v1.9.0 including customizable issue report link text (with default text is update)

**Comment by rhysd** [comment]
@jhnferraris Please note that I renamed `bug_text` property to `bug_link_text` because it's more obvious.

**Comment by jhnferraris** [comment]
@rhysd Thanks dude!

**Comment by will-stone** [comment]
@rhysd nice one. Thanks!

**Pull request merged**
